### ISSUE TITLE
Access to the rendered handsontable

### ISSUE THREAD

**Issue by ShaheedHaque** [pyexcel-renderers/pyexcel-handsontable#1]
One big practical issue I had with this rather lovely piece of work is that no handle is kept to the generated handsontable since the constructor is called as follows:

`
  new Handsontable(pyexcelElement, actualconfig);
`

This is especially annoying when multiple workbooks with multiple sheets are in use. Not only is it hard (and fragile) to find the relevant items in the DOM, adding listeners etc. to hook into the facilities that handontable exposes is very hard. I found that a small change in the design of the JS solves this problem rather nicely as follows.

You currently create:

- 1 bookId of the form 'pyexcel-7f089d408e2045768c0bf3094a4bf98f-book'.
- N sheetIds of the form 'pyexcel-1859dbf6a97f413b928fc4705bbe715c'.
- HTML a bit like this:

```
    <!-- N Book tabs -->
    <ul class="tab" style="width:900px">
        <li id='$SHEETID$-sheet-li' class="$BOOKID$-li"></li>
    </ul>
    <!-- N Sheet divs -->
    <div id="$SHEETID$-sheet" class="tabcontent $BOOKID$">
        <div id="$SHEETID$"></div>
    </div>
```

I describe the next section in terms of the hack that I used; a proper fix could simply change the template in use (adding the new concepts of a user-defined name for the book, and a sheet number).

First, I noticed that the bookId and the first sheetId can be snarfed from the end of the JS which looks:

```
      activateFirst('$BOOKID$', '$SHEETID$-sheet');
```

Then, to expose each sheet/table, I changed each call of the constructor from this:

```
      new Handsontable(pyexcelElement, actualconfig);
```

to store the result. I also modify the newly stored handsontable to store a user-defined name for the book, the sheet number, and so on:

```
       pyexcelElement.handsontable = new Handsontable(pyexcelElement, actualconfig);
       pyexcelElement.handsontable.book = "user-defined-book-name";
       pyexcelElement.handsontable.sheet = <sheet_number>;
       pyexcelElement.handsontable.bookId = 'book_id";
       pyexcelElement.handsontable.sheetId = pyexcelElement.id;
```

Now, getting access to each sheet in each book is simple, using variations on this one selector:

```
      tabcontent = document.querySelectorAll(".tabcontent > div");
```

This allows the two following JS functions to be created to give structured access to each workbook:

```
    function getBookSheets(book) {
        var result = [];
        var sheetElements = [].slice.call(document.querySelectorAll(".tabcontent > div"));
        for (var i = 0; i < sheetElements.length; i++) {
            var sheetElement = sheetElements[i];
            if (sheetElement.handsontable.book === book) {
                result.push(sheetElement.handsontable);
            }
        }
        return result;
    }
    function getBookTabs(book) {
        var sheets = getBookSheets(book);
        if (sheets.length > 0) {
            var sheet = sheets[0];
            return [].slice.call(document.querySelectorAll(".tab > ." + sheet.bookId + "-li"));
        } else {
            return [];
        }
    }
```

I realise this needs a change to the user-visible view of your current logic, and a design change, but I really think the integration warrants it. Please consider.

**Comment by chfw** [comment]
What if pyexcelElement becomes an array of dictionaries?

```
       pyexcelElement[0].handsontable = new Handsontable(pyexcelElement, actualconfig);
       pyexcelElement[0].handsontable.book = "user-defined-book-name";
       pyexcelElement[0].handsontable.sheet = <sheet_number>;
       pyexcelElement[0].handsontable.bookId = 'book_id";
       pyexcelElement[0].handsontable.sheetId = pyexcelElement.id;
```

**Comment by ShaheedHaque** [comment]
You mean to avoid the need for the getBookSheets function? That would work. Maybe a better name such as pyexcelSheets though? What about access to the tabs? One option could be to add the tabs to the dicts too. I'm a tiny bit wary of continuing to polluting the handsontable object so maybe we end up with something like this:
```
       pyexcelSheets[0].handsontable = new Handsontable(pyexcelElement, actualconfig);
       pyexcelSheets[0].book = "user-defined-book-name";
       pyexcelSheets[0].sheet = <sheet_number>;
       pyexcelSheets[0].element = pyexcelElement;
       pyexcelSheets[0].tab = <tabLiElement>;
```
This gives direct access to the handsontable, the sheet element and the tab element. That should allow all needed manipulation to be done in JS by book and/or sheet using one function:

```
    function pyexcelBookSheets(book) {
        var result = [];
        for (var i = 0; i < pyexcelSheets.length; i++) {
            var sheetElement = sheetElements[i];
            if (sheetElement.book === book) {
                result.push(sheetElement);
            }
        }
        return result;
    }
```

**Comment by chfw** [comment]
Please try version 0.0.2. I have not included the extra two functions you proposed but otherwise you can find the created handsontables in `tableHandles` array.
