### ISSUE TITLE
Doesn't work offline.

### ISSUE THREAD

**Issue by patarapolw** [pyexcel-renderers/pyexcel-handsontable#2]
I have tried turning off my WiFi, and nothing appears.

This project, actually [TagDict](https://github.com/patarapolw/TagDict).

**Comment by chfw** [comment]
here's offline example: https://github.com/pyexcel-renderers/pyexcel-handsontable/blob/master/demo/demo.py

**Comment by patarapolw** [comment]
Thanks. I will download the `*.js` and `*.css` to my offline.
