### ISSUE TITLE
It is possible to view HTML/markdown in handsontable?

### ISSUE THREAD

**Issue by patarapolw** [pyexcel-renderers/pyexcel-handsontable#3]
And if there is an image, thumbnailize the image.

If know it is a little unusual to have HTML/markdown inside an Excel sheet, but I am doing this project. - https://github.com/patarapolw/jupyter-flashcards

Also, another feature I am interested in would be, limiting the column width/wrap text.

**Comment by chfw** [comment]
maybe possible. you need to read : https://handsontable.com/examples?manual-resize&manual-move&conditional-formatting&context-menu&filters&dropdown-menu&headers

And the try to tweak this library's options for handsontable.

**Comment by patarapolw** [comment]
From here -- https://docs.handsontable.com/5.0.0/demo-custom-renderers.html#page-cell

I want this supported.

    hot1 = new Handsontable(container1, {
      data: data,
      colWidths: [200, 200, 200, 80],
      colHeaders: ["Title", "Description", "Comments", "Cover"],
      columns: [
        {data: "title", renderer: "html"},
        {data: "description", renderer: "html"},
        {data: "comments", renderer: safeHtmlRenderer},
        {data: "cover", renderer: coverRenderer}
      ]
    });

Not just:

    var actualconfig = Object.assign({}, config);
    actualconfig["data"] = mydata;
    new Handsontable(pyexcelElement, actualconfig);

It seems that only the "data" key is filled here.

OK, I've tested that this works...

    pyexcel.save_as(
        array=data,
        dest_file_name='test.handsontable.html'
    )

    html_target = [1, 2]

    columns = list()
    for i, header_item in enumerate(data[0]):
        if i in html_target:
            columns.append({"data": i, "renderer": "html"})
        else:
            columns.append({"data": i})
    columnsJson = json.dumps(columns)

    with open('test.handsontable.html', 'r+') as f:
        contents = f.readlines()
        for i, row in enumerate(contents):
            if 'actualconfig["data"] = mydata;' in row:
                contents.insert(i+1, f'''
    actualconfig["colHeaders"] = {data[0]};
    actualconfig["columns"] = {columnsJson};
                ''')
                break

        f.seek(0)
        f.write(''.join(contents))

It seems that `colHeaders` and `readOnly` is not working without the tweak.

**Comment by chfw** [comment]
Will consider getting it into 0.0.2

**Comment by patarapolw** [comment]
I made it in my new repo, https://github.com/patarapolw/pyhandsontable and https://github.com/patarapolw/gflashcards/blob/master/gflashcards/app.py#L79

**Comment by chfw** [comment]
please try it out with pyexcel-handsontable version 0.0.2

```
styles = {
  "your sheet": {
    "colHeaders": [ "your", "header"],
    ... /*any handonsontable configurations*/
  }
}
```
