### ISSUE TITLE
Save button

### ISSUE THREAD

**Issue by patarapolw** [pyexcel-renderers/pyexcel-handsontable#4]
Please consider adding a save button after editing, back to pyexcel: https://docs.handsontable.com/5.0.0/tutorial-load-and-save.html

**Comment by chfw** [comment]
this will be a big use case!

A server needs to be written to receive the changes and a javascript logics shall be written to collect the changes. In the end, pyexcel write the changes somewhere in server side.

**Comment by patarapolw** [comment]
For what I have tried, see https://github.com/patarapolw/simplecel
